In [2]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [3]:
data_raw = pd.read_csv('../data/results.csv')

In [4]:
data_raw['tournament'].value_counts()

tournament
Friendly                                18252
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1036
                                        ...
TIFOCO Tournament                           1
Copa Confraternidad                         1
Benedikt Fontana Cup                        1
ConIFA Challenger Cup                       1
South Asian Super Cup                       1
Name: count, Length: 193, dtype: int64

In [5]:
world_cup_data_full = data_raw[data_raw["tournament"].str.startswith("FIFA World Cup", na=False)]
world_cup_data_full

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
1486,1930-07-13,Belgium,United States,0.0,3.0,FIFA World Cup,Montevideo,Uruguay,True
1487,1930-07-13,France,Mexico,4.0,1.0,FIFA World Cup,Montevideo,Uruguay,True
1488,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True
1489,1930-07-14,Peru,Romania,1.0,3.0,FIFA World Cup,Montevideo,Uruguay,True
1490,1930-07-15,Argentina,France,1.0,0.0,FIFA World Cup,Montevideo,Uruguay,True
...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [6]:
world_cup_data_full['date'] = pd.to_datetime(world_cup_data_full['date'])

In [7]:
world_cup_data_full['year'] = world_cup_data_full['date'].dt.year
world_cup_data_full

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
1486,1930-07-13,Belgium,United States,0.0,3.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1487,1930-07-13,France,Mexico,4.0,1.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1488,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1489,1930-07-14,Peru,Romania,1.0,3.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1490,1930-07-15,Argentina,France,1.0,0.0,FIFA World Cup,Montevideo,Uruguay,True,1930
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [8]:
world_cup_data = world_cup_data_full[world_cup_data_full['year'] > 1990]
world_cup_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
18164,1992-03-21,Dominican Republic,Puerto Rico,1.0,2.0,FIFA World Cup qualification,Santo Domingo,Dominican Republic,False,1992
18166,1992-03-22,Saint Lucia,Saint Vincent and the Grenadines,1.0,0.0,FIFA World Cup qualification,Castries,Saint Lucia,False,1992
18176,1992-03-29,Puerto Rico,Dominican Republic,1.0,1.0,FIFA World Cup qualification,San Juan,Puerto Rico,False,1992
18177,1992-03-29,Saint Vincent and the Grenadines,Saint Lucia,3.0,1.0,FIFA World Cup qualification,Kingstown,Saint Vincent and the Grenadines,False,1992
18194,1992-04-19,Barbados,Trinidad and Tobago,1.0,2.0,FIFA World Cup qualification,Bridgetown,Barbados,False,1992
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [9]:
world_cup_data.to_csv('../data/ProcessedDataForTestModel/ResultsFrom1990.csv', index = False)

In [10]:
world_cup_data.info()

<class 'pandas.DataFrame'>
Index: 7549 entries, 18164 to 49286
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        7549 non-null   datetime64[us]
 1   home_team   7549 non-null   str
 2   away_team   7549 non-null   str
 3   home_score  7477 non-null   float64
 4   away_score  7477 non-null   float64
 5   tournament  7549 non-null   str
 6   city        7549 non-null   str
 7   country     7549 non-null   str
 8   neutral     7549 non-null   bool
 9   year        7549 non-null   int32
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), str(5)
memory usage: 567.6 KB

In [11]:
world_cup_data.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral', 'year'],
      dtype='str')

In [12]:
world_cup_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
18164,1992-03-21,Dominican Republic,Puerto Rico,1.0,2.0,FIFA World Cup qualification,Santo Domingo,Dominican Republic,False,1992
18166,1992-03-22,Saint Lucia,Saint Vincent and the Grenadines,1.0,0.0,FIFA World Cup qualification,Castries,Saint Lucia,False,1992
18176,1992-03-29,Puerto Rico,Dominican Republic,1.0,1.0,FIFA World Cup qualification,San Juan,Puerto Rico,False,1992
18177,1992-03-29,Saint Vincent and the Grenadines,Saint Lucia,3.0,1.0,FIFA World Cup qualification,Kingstown,Saint Vincent and the Grenadines,False,1992
18194,1992-04-19,Barbados,Trinidad and Tobago,1.0,2.0,FIFA World Cup qualification,Bridgetown,Barbados,False,1992
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [13]:
world_cup_data['year'].unique()

array([1992, 1993, 1994, 1996, 1997, 1998, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
      dtype=int32)

In [17]:
data_from_2000 = world_cup_data[world_cup_data['year']>1999].copy()
data_from_2000[ (data_from_2000['year'] == 2026) & (data_from_2000['tournament']=='FIFA World Cup')]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
49215,2026-06-11,Mexico,South Africa,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False,2026
49216,2026-06-11,South Korea,Czech Republic,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True,2026
49217,2026-06-12,Canada,Bosnia and Herzegovina,NaN,NaN,FIFA World Cup,Toronto,Canada,False,2026
49218,2026-06-12,United States,Paraguay,NaN,NaN,FIFA World Cup,Inglewood,United States,False,2026
49219,2026-06-13,Qatar,Switzerland,NaN,NaN,FIFA World Cup,Santa Clara,United States,True,2026
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [18]:
## THis dataset already has all the 72 matches that will be played in the WC in the group stage so we should remove these 72 rows because this will be our test data

test_demo_data = data_from_2000[ (data_from_2000['year'] == 2026) & (data_from_2000['tournament']=='FIFA World Cup')].copy()

In [21]:
test_demo_data.info()

<class 'pandas.DataFrame'>
Index: 72 entries, 49215 to 49286
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        72 non-null     datetime64[us]
 1   home_team   72 non-null     str
 2   away_team   72 non-null     str
 3   home_score  0 non-null      float64
 4   away_score  0 non-null      float64
 5   tournament  72 non-null     str
 6   city        72 non-null     str
 7   country     72 non-null     str
 8   neutral     72 non-null     bool
 9   year        72 non-null     int32
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), str(5)
memory usage: 5.4 KB

In [22]:
test_demo_data.to_csv('../data/ProcessedDataForTestModel/test_demo_data.csv')

In [23]:
historical_train_data = data_from_2000.drop(index=test_demo_data.index).copy()
historical_train_data.info()

<class 'pandas.DataFrame'>
Index: 6224 entries, 24242 to 49211
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        6224 non-null   datetime64[us]
 1   home_team   6224 non-null   str
 2   away_team   6224 non-null   str
 3   home_score  6224 non-null   float64
 4   away_score  6224 non-null   float64
 5   tournament  6224 non-null   str
 6   city        6224 non-null   str
 7   country     6224 non-null   str
 8   neutral     6224 non-null   bool
 9   year        6224 non-null   int32
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), str(5)
memory usage: 468.0 KB

In [24]:
historical_train_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
24242,2000-03-04,Honduras,Nicaragua,3.0,0.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False,2000
24243,2000-03-04,Trinidad and Tobago,Curaçao,5.0,0.0,FIFA World Cup qualification,Macoya,Trinidad and Tobago,False,2000
24244,2000-03-05,Anguilla,Bahamas,1.0,3.0,FIFA World Cup qualification,The Valley,Anguilla,False,2000
24245,2000-03-05,Barbados,Grenada,2.0,2.0,FIFA World Cup qualification,Bridgetown,Barbados,False,2000
24247,2000-03-05,British Virgin Islands,Bermuda,1.0,5.0,FIFA World Cup qualification,Road Town,British Virgin Islands,False,2000
...,...,...,...,...,...,...,...,...,...,...
49207,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,True,2026
49208,2026-03-31,Bosnia and Herzegovina,Italy,1.0,1.0,FIFA World Cup qualification,Zenica,Bosnia and Herzegovina,False,2026
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,2026
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,2026
49211,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False,2026

In [25]:
historical_train_data.to_csv("../data/ProcessedDataForTestModel/historical_train_data.csv")