In [108]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

In [109]:
data_raw = pd.read_csv('../data/results.csv')

In [110]:
data_raw['tournament'].value_counts()

tournament
Friendly                                18252
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1036
                                        ...
TIFOCO Tournament                           1
Copa Confraternidad                         1
Benedikt Fontana Cup                        1
ConIFA Challenger Cup                       1
South Asian Super Cup                       1
Name: count, Length: 193, dtype: int64

In [111]:
world_cup_data_full = data_raw[data_raw["tournament"].str.startswith("FIFA World Cup", na=False)]
world_cup_data_full

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
1486,1930-07-13,Belgium,United States,0.0,3.0,FIFA World Cup,Montevideo,Uruguay,True
1487,1930-07-13,France,Mexico,4.0,1.0,FIFA World Cup,Montevideo,Uruguay,True
1488,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True
1489,1930-07-14,Peru,Romania,1.0,3.0,FIFA World Cup,Montevideo,Uruguay,True
1490,1930-07-15,Argentina,France,1.0,0.0,FIFA World Cup,Montevideo,Uruguay,True
...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [112]:
world_cup_data_full['date'] = pd.to_datetime(world_cup_data_full['date'])

In [113]:
world_cup_data_full['year'] = world_cup_data_full['date'].dt.year
world_cup_data_full

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
1486,1930-07-13,Belgium,United States,0.0,3.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1487,1930-07-13,France,Mexico,4.0,1.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1488,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1489,1930-07-14,Peru,Romania,1.0,3.0,FIFA World Cup,Montevideo,Uruguay,True,1930
1490,1930-07-15,Argentina,France,1.0,0.0,FIFA World Cup,Montevideo,Uruguay,True,1930
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [114]:
world_cup_data = world_cup_data_full[world_cup_data_full['year'] > 1990]
world_cup_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
18164,1992-03-21,Dominican Republic,Puerto Rico,1.0,2.0,FIFA World Cup qualification,Santo Domingo,Dominican Republic,False,1992
18166,1992-03-22,Saint Lucia,Saint Vincent and the Grenadines,1.0,0.0,FIFA World Cup qualification,Castries,Saint Lucia,False,1992
18176,1992-03-29,Puerto Rico,Dominican Republic,1.0,1.0,FIFA World Cup qualification,San Juan,Puerto Rico,False,1992
18177,1992-03-29,Saint Vincent and the Grenadines,Saint Lucia,3.0,1.0,FIFA World Cup qualification,Kingstown,Saint Vincent and the Grenadines,False,1992
18194,1992-04-19,Barbados,Trinidad and Tobago,1.0,2.0,FIFA World Cup qualification,Bridgetown,Barbados,False,1992
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [115]:
world_cup_data.to_csv('../data/ProcessedDataForTestModel/ResultsFrom1990.csv', index = False)

In [116]:
world_cup_data.info()

<class 'pandas.DataFrame'>
Index: 7549 entries, 18164 to 49286
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        7549 non-null   datetime64[us]
 1   home_team   7549 non-null   str
 2   away_team   7549 non-null   str
 3   home_score  7477 non-null   float64
 4   away_score  7477 non-null   float64
 5   tournament  7549 non-null   str
 6   city        7549 non-null   str
 7   country     7549 non-null   str
 8   neutral     7549 non-null   bool
 9   year        7549 non-null   int32
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), str(5)
memory usage: 567.6 KB

In [117]:
world_cup_data.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral', 'year'],
      dtype='str')

In [118]:
world_cup_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
18164,1992-03-21,Dominican Republic,Puerto Rico,1.0,2.0,FIFA World Cup qualification,Santo Domingo,Dominican Republic,False,1992
18166,1992-03-22,Saint Lucia,Saint Vincent and the Grenadines,1.0,0.0,FIFA World Cup qualification,Castries,Saint Lucia,False,1992
18176,1992-03-29,Puerto Rico,Dominican Republic,1.0,1.0,FIFA World Cup qualification,San Juan,Puerto Rico,False,1992
18177,1992-03-29,Saint Vincent and the Grenadines,Saint Lucia,3.0,1.0,FIFA World Cup qualification,Kingstown,Saint Vincent and the Grenadines,False,1992
18194,1992-04-19,Barbados,Trinidad and Tobago,1.0,2.0,FIFA World Cup qualification,Bridgetown,Barbados,False,1992
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [119]:
world_cup_data['year'].unique()

array([1992, 1993, 1994, 1996, 1997, 1998, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
      dtype=int32)

In [120]:
data_from_2000 = world_cup_data[world_cup_data['year']>1999].copy()
data_from_2000[ (data_from_2000['year'] == 2026) & (data_from_2000['tournament']=='FIFA World Cup')]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
49215,2026-06-11,Mexico,South Africa,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False,2026
49216,2026-06-11,South Korea,Czech Republic,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True,2026
49217,2026-06-12,Canada,Bosnia and Herzegovina,NaN,NaN,FIFA World Cup,Toronto,Canada,False,2026
49218,2026-06-12,United States,Paraguay,NaN,NaN,FIFA World Cup,Inglewood,United States,False,2026
49219,2026-06-13,Qatar,Switzerland,NaN,NaN,FIFA World Cup,Santa Clara,United States,True,2026
...,...,...,...,...,...,...,...,...,...,...
49282,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True,2026
49283,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True,2026
49284,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True,2026
49285,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True,2026
49286,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True,2026

In [121]:
## THis dataset already has all the 72 matches that will be played in the WC in the group stage so we should remove these 72 rows because this will be our test data

test_demo_data = data_from_2000[ (data_from_2000['year'] == 2026) & (data_from_2000['tournament']=='FIFA World Cup')].copy()

In [122]:
test_demo_data.info()

<class 'pandas.DataFrame'>
Index: 72 entries, 49215 to 49286
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        72 non-null     datetime64[us]
 1   home_team   72 non-null     str
 2   away_team   72 non-null     str
 3   home_score  0 non-null      float64
 4   away_score  0 non-null      float64
 5   tournament  72 non-null     str
 6   city        72 non-null     str
 7   country     72 non-null     str
 8   neutral     72 non-null     bool
 9   year        72 non-null     int32
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), str(5)
memory usage: 5.4 KB

In [123]:
test_demo_data.to_csv('../data/ProcessedDataForTestModel/prediction_data.csv')

In [124]:
historical_train_data = data_from_2000.drop(index=test_demo_data.index).copy()
historical_train_data.info()

<class 'pandas.DataFrame'>
Index: 6224 entries, 24242 to 49211
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        6224 non-null   datetime64[us]
 1   home_team   6224 non-null   str
 2   away_team   6224 non-null   str
 3   home_score  6224 non-null   float64
 4   away_score  6224 non-null   float64
 5   tournament  6224 non-null   str
 6   city        6224 non-null   str
 7   country     6224 non-null   str
 8   neutral     6224 non-null   bool
 9   year        6224 non-null   int32
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), str(5)
memory usage: 468.0 KB

In [125]:
historical_train_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
24242,2000-03-04,Honduras,Nicaragua,3.0,0.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False,2000
24243,2000-03-04,Trinidad and Tobago,Curaçao,5.0,0.0,FIFA World Cup qualification,Macoya,Trinidad and Tobago,False,2000
24244,2000-03-05,Anguilla,Bahamas,1.0,3.0,FIFA World Cup qualification,The Valley,Anguilla,False,2000
24245,2000-03-05,Barbados,Grenada,2.0,2.0,FIFA World Cup qualification,Bridgetown,Barbados,False,2000
24247,2000-03-05,British Virgin Islands,Bermuda,1.0,5.0,FIFA World Cup qualification,Road Town,British Virgin Islands,False,2000
...,...,...,...,...,...,...,...,...,...,...
49207,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,True,2026
49208,2026-03-31,Bosnia and Herzegovina,Italy,1.0,1.0,FIFA World Cup qualification,Zenica,Bosnia and Herzegovina,False,2026
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,2026
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,2026
49211,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False,2026

In [126]:
historical_train_data.to_csv("../data/ProcessedDataForTestModel/historical_train_data.csv")

In [127]:
## Okay after two demos, we need to update our features before creating a third demo version:
## Firstly we will start by using only the matches from 2022 till now

historical_match_data = historical_train_data[historical_train_data['year']>=2022].copy()
historical_match_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year
44864,2022-01-27,Jamaica,Mexico,1.0,2.0,FIFA World Cup qualification,Kingston,Jamaica,False,2022
44865,2022-01-27,United States,El Salvador,1.0,0.0,FIFA World Cup qualification,Columbus,United States,False,2022
44866,2022-01-27,Honduras,Canada,0.0,2.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False,2022
44867,2022-01-27,Costa Rica,Panama,1.0,0.0,FIFA World Cup qualification,San José,Costa Rica,False,2022
44868,2022-01-27,Lebanon,South Korea,0.0,1.0,FIFA World Cup qualification,Sidon,Lebanon,False,2022
...,...,...,...,...,...,...,...,...,...,...
49207,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,True,2026
49208,2026-03-31,Bosnia and Herzegovina,Italy,1.0,1.0,FIFA World Cup qualification,Zenica,Bosnia and Herzegovina,False,2026
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,2026
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,2026
49211,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False,2026

In [128]:
historical_match_data['is_world_cup'] = (historical_match_data['tournament']=='FIFA World Cup').astype(int) ## Meaning: 1 is World Cup match, 0 is not
historical_match_data['is_qualifier'] = (historical_match_data['tournament'] == 'FIFA World Cup qualification').astype(int) ## Meaning: same logic as the world cup column
historical_match_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,is_world_cup,is_qualifier
44864,2022-01-27,Jamaica,Mexico,1.0,2.0,FIFA World Cup qualification,Kingston,Jamaica,False,2022,0,1
44865,2022-01-27,United States,El Salvador,1.0,0.0,FIFA World Cup qualification,Columbus,United States,False,2022,0,1
44866,2022-01-27,Honduras,Canada,0.0,2.0,FIFA World Cup qualification,San Pedro Sula,Honduras,False,2022,0,1
44867,2022-01-27,Costa Rica,Panama,1.0,0.0,FIFA World Cup qualification,San José,Costa Rica,False,2022,0,1
44868,2022-01-27,Lebanon,South Korea,0.0,1.0,FIFA World Cup qualification,Sidon,Lebanon,False,2022,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
49207,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,True,2026,0,1
49208,2026-03-31,Bosnia and Herzegovina,Italy,1.0,1.0,FIFA World Cup qualification,Zenica,Bosnia and Herzegovina,False,2026,0,1
49209,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,2026,0,1
49210,2026-03-31,Kosovo,Turkey,0.0,1.0,FIFA World Cup qualification,Pristina,Kosovo,False,2026,0,1
49211,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False,2026,0,1

In [129]:
historical_match_data['date'] = pd.to_datetime(historical_match_data['date'])
historical_match_data = historical_match_data.sort_values('date').reset_index(drop=True)
historical_match_data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,is_world_cup,is_qualifier
0,2022-01-27,Jamaica,Mexico,1.0,2.0,FIFA World Cup qualification,Kingston,Jamaica,False,2022,0,1
1,2022-01-27,Chile,Argentina,1.0,2.0,FIFA World Cup qualification,Calama,Chile,False,2022,0,1
2,2022-01-27,Paraguay,Uruguay,0.0,1.0,FIFA World Cup qualification,Asunción,Paraguay,False,2022,0,1
3,2022-01-27,Ecuador,Brazil,1.0,1.0,FIFA World Cup qualification,Quito,Ecuador,False,2022,0,1
4,2022-01-27,Saudi Arabia,Oman,1.0,0.0,FIFA World Cup qualification,Jeddah,Saudi Arabia,False,2022,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1060,2026-03-31,DR Congo,Jamaica,1.0,0.0,FIFA World Cup qualification,Zapopan,Mexico,True,2026,0,1
1061,2026-03-31,Iraq,Bolivia,2.0,1.0,FIFA World Cup qualification,Guadalupe,Mexico,True,2026,0,1
1062,2026-03-31,Bosnia and Herzegovina,Italy,1.0,1.0,FIFA World Cup qualification,Zenica,Bosnia and Herzegovina,False,2026,0,1
1063,2026-03-31,Sweden,Poland,3.0,2.0,FIFA World Cup qualification,Solna,Sweden,False,2026,0,1
1064,2026-03-31,Czech Republic,Denmark,2.0,2.0,FIFA World Cup qualification,Prague,Czech Republic,False,2026,0,1

In [130]:
historical_match_data['home_team'].unique()

<StringArray>
[            'Jamaica',               'Chile',            'Paraguay',
             'Ecuador',        'Saudi Arabia',               'Japan',
           'Australia',                'Iran',             'Lebanon',
          'Costa Rica',
 ...
            'Slovenia',               'Congo', 'Republic of Ireland',
             'Armenia',              'Turkey',             'Belarus',
              'Kosovo',          'Azerbaijan',             'Hungary',
    'Northern Ireland']
Length: 206, dtype: str

In [131]:
historical_match_data['neutral'] = historical_match_data['neutral'].astype(int)
historical_match_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1065 entries, 0 to 1064
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1065 non-null   datetime64[us]
 1   home_team     1065 non-null   str
 2   away_team     1065 non-null   str
 3   home_score    1065 non-null   float64
 4   away_score    1065 non-null   float64
 5   tournament    1065 non-null   str
 6   city          1065 non-null   str
 7   country       1065 non-null   str
 8   neutral       1065 non-null   int64
 9   year          1065 non-null   int32
 10  is_world_cup  1065 non-null   int64
 11  is_qualifier  1065 non-null   int64
dtypes: datetime64[us](1), float64(2), int32(1), int64(3), str(5)
memory usage: 95.8 KB

In [132]:
## Now we are going to add a few features that are going to help our prediction model
## Firstly we should add the FIFA ranking at time of match, for that we are going to find the data from the FIFA official website if the data is available still

In [133]:
import time
import requests
import pandas as pd
from pathlib import Path
from urllib.parse import urlparse, parse_qs

In [134]:
data_id=["id13505"]

session = requests.Session()

session.headers.update(
    {
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://inside.fifa.com/fifa-world-ranking/men",
        "Origin": "https://inside.fifa.com",
    }
)

In [135]:
def download_fifa_ranking_snapshot(date_id):
    candidate_api_urls = [
        f"https://inside.fifa.com/api/ranking-overview?locale=en&dateId={date_id}",
        f"https://www.fifa.com/api/ranking-overview?locale=en&dateId={date_id}",
    ]

    for api_url in candidate_api_urls:
        response = session.get(api_url, timeout=30)

        content_type = response.headers.get("Content-Type", "")
        print(date_id, response.status_code, content_type, api_url)

        if response.status_code != 200:
            continue

        text_start = response.text.strip()[:30].lower()
        if text_start.startswith("<!doctype") or text_start.startswith("<html"):
            print("Skipping HTML response.")
            continue

        try:
            data = response.json()
        except Exception:
            print("Skipping invalid JSON response.")
            print(response.text[:500])
            continue

        rankings = data.get("rankings", [])

        if len(rankings) == 0:
            print("JSON response has 0 rankings.")
            print("Available keys:", data.keys())
            continue

        rows = []

        for item in rankings:
            ranking_item = item.get("rankingItem", {})

            rank = ranking_item.get("rank")
            previous_rank = ranking_item.get("previousRank")

            rows.append(
                {
                    "date_id": date_id,
                    "country": ranking_item.get("name"),
                    "country_code": ranking_item.get("countryCode"),
                    "rank": rank,
                    "previous_rank": previous_rank,
                    "rank_change": (
                        previous_rank - rank
                        if previous_rank is not None and rank is not None
                        else None
                    ),
                    "total_points": ranking_item.get("totalPoints"),
                    "previous_points": item.get("previousPoints"),
                    "confederation": item.get("tag", {}).get("text"),
                }
            )

        return pd.DataFrame(rows)

    raise RuntimeError(f"Could not download valid FIFA ranking table for date_id={date_id}")

In [136]:
df_ranking = download_fifa_ranking_snapshot(date_id)

df_ranking.head()

id14597 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14597

,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,confederation
0,id14597,Argentina,ARG,1.0,1.0,0.0,1867.25,1867.25,CONMEBOL
1,id14597,France,FRA,2.0,2.0,0.0,1859.78,1859.78,UEFA
2,id14597,Spain,ESP,3.0,3.0,0.0,1853.27,1853.27,UEFA
3,id14597,England,ENG,4.0,4.0,0.0,1813.81,1813.81,UEFA
4,id14597,Brazil,BRA,5.0,5.0,0.0,1775.85,1775.85,CONMEBOL

In [137]:
historical_match_data.to_csv('../data/ProcessedDataForTestModel/historical_match_data_2022_present.csv')

In [138]:
import time
import requests
import pandas as pd
from pathlib import Path

In [139]:
# FIFA rankings that still use the old idXXXXX format.
# The keys are the true ranking dates, and the values are the FIFA dateIds.

ranking_date_ids = {
    "2021-12-23":"id13505",
    "2022-02-10": "id13554",
    "2022-03-31": "id13603",
    "2023-07-20": "id14079",
    "2023-09-21": "id14142",
    "2023-10-26": "id14177",
    "2024-02-15": "id14289",
    "2024-04-04": "id14338",
    "2024-07-18": "id14443",
    "2024-09-19": "id14506",
    "2024-10-24": "id14541",
    "2024-12-19": "id14597",
}

In [140]:
output_dir = Path("../data/fifa_rankings")
output_dir.mkdir(parents=True, exist_ok=True)

session = requests.Session()

session.headers.update(
    {
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://inside.fifa.com/fifa-world-ranking/men",
        "Origin": "https://inside.fifa.com",
    }
)

In [141]:
def download_fifa_ranking_snapshot(rank_date, date_id):
    candidate_api_urls = [
        f"https://inside.fifa.com/api/ranking-overview?locale=en&dateId={date_id}",
        f"https://www.fifa.com/api/ranking-overview?locale=en&dateId={date_id}",
    ]

    for api_url in candidate_api_urls:
        response = session.get(api_url, timeout=30)

        content_type = response.headers.get("Content-Type", "")
        print(rank_date, date_id, response.status_code, content_type, api_url)

        if response.status_code != 200:
            continue

        text_start = response.text.strip()[:30].lower()

        if text_start.startswith("<!doctype") or text_start.startswith("<html"):
            print("Skipping HTML response.")
            continue

        try:
            data = response.json()
        except Exception:
            print("Skipping invalid JSON response.")
            print(response.text[:500])
            continue

        rankings = data.get("rankings", [])

        if len(rankings) == 0:
            print("Skipping because JSON contains 0 rankings.")
            print("Available keys:", data.keys())
            continue

        rows = []

        for item in rankings:
            ranking_item = item.get("rankingItem", {})

            rank = ranking_item.get("rank")
            previous_rank = ranking_item.get("previousRank")

            rows.append(
                {
                    "rank_date": rank_date,
                    "date_id": date_id,
                    "country": ranking_item.get("name"),
                    "country_code": ranking_item.get("countryCode"),
                    "rank": rank,
                    "previous_rank": previous_rank,
                    "rank_change": (
                        previous_rank - rank
                        if previous_rank is not None and rank is not None
                        else None
                    ),
                    "total_points": ranking_item.get("totalPoints"),
                    "previous_points": item.get("previousPoints"),
                    "confederation": item.get("tag", {}).get("text"),
                    "source_url": f"https://inside.fifa.com/fifa-world-ranking/men?dateId={date_id}",
                }
            )

        df = pd.DataFrame(rows)

        df["rank_date"] = pd.to_datetime(df["rank_date"])

        df = df[
            [
                "rank_date",
                "date_id",
                "country",
                "country_code",
                "rank",
                "previous_rank",
                "rank_change",
                "total_points",
                "previous_points",
                "confederation",
                "source_url",
            ]
        ]

        return df

    raise RuntimeError(f"Could not download valid ranking for {rank_date}, {date_id}")

In [142]:
ranking_dfs = []

for rank_date, date_id in ranking_date_ids.items():
    df = download_fifa_ranking_snapshot(rank_date, date_id)

    output_path = output_dir / f"fifa_ranking_{rank_date}.csv"

    df.to_csv(output_path, index=False)

    ranking_dfs.append(df)

    print(f"Saved {output_path} with {len(df)} teams")

    time.sleep(1.0)

2021-12-23 id13505 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id13505
Saved ../data/fifa_rankings/fifa_ranking_2021-12-23.csv with 210 teams
2022-02-10 id13554 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id13554
Saved ../data/fifa_rankings/fifa_ranking_2022-02-10.csv with 210 teams
2022-03-31 id13603 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id13603
Saved ../data/fifa_rankings/fifa_ranking_2022-03-31.csv with 211 teams
2023-07-20 id14079 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14079
Saved ../data/fifa_rankings/fifa_ranking_2023-07-20.csv with 208 teams
2023-09-21 id14142 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14142
Saved ../data/fifa_rankings/fifa_ranking_2023-09-21.csv with 207 teams
2023-10-26 id14177 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14177
Saved ../data/fifa_rankings/fifa_ranking_2023-10-26.csv with 211 teams
2024-02-15 id14289 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14289
Saved ../data/fifa_rankings/fifa_ranking_2024-02-15.csv with 211 teams
2024-04-04 id14338 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14338
Saved ../data/fifa_rankings/fifa_ranking_2024-04-04.csv with 211 teams
2024-07-18 id14443 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14443
Saved ../data/fifa_rankings/fifa_ranking_2024-07-18.csv with 211 teams
2024-09-19 id14506 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14506
Saved ../data/fifa_rankings/fifa_ranking_2024-09-19.csv with 211 teams
2024-10-24 id14541 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14541
Saved ../data/fifa_rankings/fifa_ranking_2024-10-24.csv with 211 teams
2024-12-19 id14597 200 application/json; charset=utf-8 https://inside.fifa.com/api/ranking-overview?locale=en&dateId=id14597
Saved ../data/fifa_rankings/fifa_ranking_2024-12-19.csv with 211 teams

In [143]:
fifa_rankings_2022_2024 = pd.concat(ranking_dfs, ignore_index=True)

combined_path = output_dir / "fifa_rankings_2022_2024_required_snapshots.csv"

fifa_rankings_2022_2024.to_csv(combined_path, index=False)

print(f"Saved combined file: {combined_path}")
print(fifa_rankings_2022_2024.shape)

Saved combined file: ../data/fifa_rankings/fifa_rankings_2022_2024_required_snapshots.csv
(2523, 11)

In [144]:
fifa_rankings_2022_2024.groupby("rank_date").size()

rank_date
2021-12-23    210
2022-02-10    210
2022-03-31    211
2023-07-20    208
2023-09-21    207
2023-10-26    211
2024-02-15    211
2024-04-04    211
2024-07-18    211
2024-09-19    211
2024-10-24    211
2024-12-19    211
dtype: int64

In [145]:
fifa_rankings_2022_2024.sort_values('rank_date', ascending=True)

,rank_date,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,confederation,source_url
0,2021-12-23,id13505,Belgium,BEL,1.0,1.0,0.0,1828.45,1828.45,UEFA,https://inside.fifa.com/fifa-world-ranking/men...
134,2021-12-23,id13505,Rwanda,RWA,135.0,135.0,0.0,1095.34,1095.34,CAF,https://inside.fifa.com/fifa-world-ranking/men...
135,2021-12-23,id13505,Lithuania,LTU,136.0,136.0,0.0,1091.77,1091.77,UEFA,https://inside.fifa.com/fifa-world-ranking/men...
136,2021-12-23,id13505,Ethiopia,ETH,137.0,137.0,0.0,1087.89,1087.89,CAF,https://inside.fifa.com/fifa-world-ranking/men...
137,2021-12-23,id13505,St. Kitts and Nevis,SKN,138.0,138.0,0.0,1077.76,1077.76,CONCACAF,https://inside.fifa.com/fifa-world-ranking/men...
...,...,...,...,...,...,...,...,...,...,...,...
2385,2024-12-19,id14597,Bosnia and Herzegovina,BIH,74.0,74.0,0.0,1326.69,1326.69,UEFA,https://inside.fifa.com/fifa-world-ranking/men...
2386,2024-12-19,id14597,Honduras,HON,75.0,75.0,0.0,1325.93,1325.93,CONCACAF,https://inside.fifa.com/fifa-world-ranking/men...
2387,2024-12-19,id14597,Israel,ISR,76.0,76.0,0.0,1322.25,1322.25,UEFA,https://inside.fifa.com/fifa-world-ranking/men...
2389,2024-12-19,id14597,Guinea,GUI,78.0,78.0,0.0,1311.88,1311.88,CAF,https://inside.fifa.com/fifa-world-ranking/men...
2522,2024-12-19,id14597,Eritrea,ERI,NaN,NaN,NaN,855.56,0.00,CAF,https://inside.fifa.com/fifa-world-ranking/men...

In [146]:
fifa_rankings_2022_2024.isnull().sum()

rank_date           0
date_id             0
country             0
country_code        0
rank               10
previous_rank      11
rank_change        11
total_points        0
previous_points     0
confederation       0
source_url          0
dtype: int64

In [147]:
import re
ranking_periods_2025_2026 = {
    "2025-04-03": "03 April 2025",
    "2025-07-10": "10 July 2025",
    "2025-09-18": "18 September 2025",
    #"2025-10-17": "17 October 2025",
    "2026-01-19": "19 January 2026",
    "2026-04-01": "01 April 2026",
}

In [148]:
def parse_first_number(value):
    value = str(value)

    # Remove spaces and non-breaking spaces
    value = value.replace("\xa0", " ").strip()

    # Find numbers like:
    # 1877.6
    # 1,877.6
    # 1877
    # -12.5
    match = re.search(r"[-+]?\d+(?:,\d{3})*(?:\.\d+)?", value)

    if match is None:
        return None

    return float(match.group(0).replace(",", ""))


def parse_rank(value):
    value = str(value)
    match = re.search(r"\d+", value)

    if match is None:
        return None

    return int(match.group(0))


def parse_team_and_code(value):
    value = str(value).strip()

    # Examples this is designed to handle:
    # "Brazil (BRA)"
    # "Brazil BRA"
    # "Brazil"
    match = re.search(r"^(.*?)\s*\(([A-Z]{2,4})\)", value)

    if match is not None:
        return match.group(1).strip(), match.group(2).strip()

    match = re.search(r"^(.*?)\s+([A-Z]{2,4})$", value)

    if match is not None:
        return match.group(1).strip(), match.group(2).strip()

    return value, None

In [149]:
def find_ranking_table(tables):
    for table in tables:
        cols = [str(c).lower() for c in table.columns]
        col_text = " ".join(cols)

        if "rank" in col_text and ("team" in col_text or "country" in col_text):
            return table.copy()

    raise RuntimeError("Could not find a ranking table. Print the tables to inspect them manually.")

In [150]:
def clean_football_ranking_table(raw_df, rank_date, period, source_url):
    df = raw_df.copy()

    df.columns = [
        str(col)
        .replace("\xa0", " ")
        .strip()
        .lower()
        for col in df.columns
    ]

    print("Columns found:", list(df.columns))

    rank_col = [c for c in df.columns if "rank" in c][0]

    team_candidates = [c for c in df.columns if "team" in c or "country" in c]
    team_col = team_candidates[0]

    point_candidates = [c for c in df.columns if "point" in c or "pts" in c]
    current_points_col = point_candidates[0] if len(point_candidates) > 0 else None

    previous_points_col = None
    for c in point_candidates:
        if "prev" in c or "previous" in c:
            previous_points_col = c
            break

    previous_rank_col = None
    for c in df.columns:
        if ("prev" in c or "previous" in c) and "rank" in c:
            previous_rank_col = c
            break

    rows = []

    for _, row in df.iterrows():
        rank = parse_rank(row[rank_col])
        country, country_code = parse_team_and_code(row[team_col])

        if rank is None:
            continue

        total_points = (
            parse_first_number(row[current_points_col])
            if current_points_col is not None
            else None
        )

        previous_points = (
            parse_first_number(row[previous_points_col])
            if previous_points_col is not None
            else None
        )

        previous_rank = (
            parse_rank(row[previous_rank_col])
            if previous_rank_col is not None
            else None
        )

        rows.append(
            {
                "rank_date": rank_date,
                "date_id": f"football_ranking_{rank_date}",
                "country": country,
                "country_code": country_code,
                "rank": rank,
                "previous_rank": previous_rank,
                "rank_change": (
                    previous_rank - rank
                    if previous_rank is not None and rank is not None
                    else None
                ),
                "total_points": total_points,
                "previous_points": previous_points,
                "confederation": None,
                "source_url": source_url,
            }
        )

    result = pd.DataFrame(rows)

    result["rank_date"] = pd.to_datetime(result["rank_date"])

    result = result[
        [
            "rank_date",
            "date_id",
            "country",
            "country_code",
            "rank",
            "previous_rank",
            "rank_change",
            "total_points",
            "previous_points",
            "confederation",
            "source_url",
        ]
    ]

    return result

In [151]:
def download_football_ranking_snapshot(rank_date, period, max_pages=5):
    period_query = period.replace(" ", "+")

    all_pages = []

    for page in range(1, max_pages + 1):
        if page == 1:
            url = f"https://football-ranking.com/ranks?period={period_query}"
        else:
            url = f"https://football-ranking.com/ranks?period={period_query}&page={page}"

        print("Reading:", url)

        tables = pd.read_html(url)
        print(f"Found {len(tables)} tables")

        raw_table = find_ranking_table(tables)

        cleaned = clean_football_ranking_table(
            raw_df=raw_table,
            rank_date=rank_date,
            period=period,
            source_url=url,
        )

        print("Page shape:", cleaned.shape)

        all_pages.append(cleaned)

        time.sleep(0.5)

    snapshot = pd.concat(all_pages, ignore_index=True)

    snapshot = (
        snapshot
        .drop_duplicates(subset=["rank"])
        .sort_values("rank")
        .reset_index(drop=True)
    )

    return snapshot

In [176]:
test_df = download_football_ranking_snapshot(
    rank_date="2026-04-01",
    period="01 April 2026",
)

test_df.head()

Reading: https://football-ranking.com/ranks?period=01+April+2026
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=2
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=3
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=4
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=5
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (10, 11)

,rank_date,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,confederation,source_url
0,2026-04-01,football_ranking_2026-04-01,France,FRA,1,3,2,1877.32,1870.0,None,https://football-ranking.com/ranks?period=01+A...
1,2026-04-01,football_ranking_2026-04-01,Spain,ESP,2,1,-1,1876.40,1877.0,None,https://football-ranking.com/ranks?period=01+A...
2,2026-04-01,football_ranking_2026-04-01,Argentina,ARG,3,2,-1,1874.82,1873.0,None,https://football-ranking.com/ranks?period=01+A...
3,2026-04-01,football_ranking_2026-04-01,England,ENG,4,4,0,1825.97,1834.0,None,https://football-ranking.com/ranks?period=01+A...
4,2026-04-01,football_ranking_2026-04-01,Portugal,POR,5,6,1,1763.83,1760.0,None,https://football-ranking.com/ranks?period=01+A...

In [153]:
test_df.shape

(210, 11)

In [154]:
test_df["rank"].min(), test_df["rank"].max(), test_df["rank"].nunique()

(np.int64(1), np.int64(210), 210)

In [155]:
missing_ranks = set(range(1, test_df["rank"].max() + 1)) - set(test_df["rank"])

sorted(missing_ranks)

[]

In [156]:
test_df.head(10)

,rank_date,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,confederation,source_url
0,2026-01-19,football_ranking_2026-01-19,Spain,ESP,1,1,0,1877.18,1877.0,None,https://football-ranking.com/ranks?period=19+J...
1,2026-01-19,football_ranking_2026-01-19,Argentina,ARG,2,2,0,1873.33,1873.0,None,https://football-ranking.com/ranks?period=19+J...
2,2026-01-19,football_ranking_2026-01-19,France,FRA,3,3,0,1870.00,1870.0,None,https://football-ranking.com/ranks?period=19+J...
3,2026-01-19,football_ranking_2026-01-19,England,ENG,4,4,0,1834.12,1834.0,None,https://football-ranking.com/ranks?period=19+J...
4,2026-01-19,football_ranking_2026-01-19,Brazil,BRA,5,5,0,1760.46,1760.0,None,https://football-ranking.com/ranks?period=19+J...
5,2026-01-19,football_ranking_2026-01-19,Portugal,POR,6,6,0,1760.38,1760.0,None,https://football-ranking.com/ranks?period=19+J...
6,2026-01-19,football_ranking_2026-01-19,Netherlands,NED,7,7,0,1756.27,1756.0,None,https://football-ranking.com/ranks?period=19+J...
7,2026-01-19,football_ranking_2026-01-19,Morocco,MAR,8,11,3,1736.56,1716.0,None,https://football-ranking.com/ranks?period=19+J...
8,2026-01-19,football_ranking_2026-01-19,Belgium,BEL,9,8,-1,1730.71,1731.0,None,https://football-ranking.com/ranks?period=19+J...
9,2026-01-19,football_ranking_2026-01-19,Germany,GER,10,9,-1,1724.15,1724.0,None,https://football-ranking.com/ranks?period=19+J...

In [157]:
ranking_dfs_2025_2026 = []

for rank_date, period in ranking_periods_2025_2026.items():
    print("\n==============================")
    print("Processing:", rank_date, period)
    print("==============================")

    df = download_football_ranking_snapshot(
        rank_date=rank_date,
        period=period,
        max_pages=5,
    )

    print("Downloaded shape:", df.shape)
    print(df.head())

    output_path = output_dir / f"fifa_ranking_{rank_date}.csv"
    df.to_csv(output_path, index=False)

    ranking_dfs_2025_2026.append(df)

    print(f"Saved {output_path} with shape {df.shape}")

==============================
Processing: 2025-04-03 03 April 2025
==============================
Reading: https://football-ranking.com/ranks?period=03+April+2025
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=03+April+2025&page=2
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=03+April+2025&page=3
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=03+April+2025&page=4
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=03+April+2025&page=5
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (10, 11)
Downloaded shape: (210, 11)
   rank_date                      date_id    country country_code  rank  \
0 2025-04-03  football_ranking_2025-04-03  Argentina          ARG     1
1 2025-04-03  football_ranking_2025-04-03     France          FRA     2
2 2025-04-03  football_ranking_2025-04-03      Spain          ESP     3
3 2025-04-03  football_ranking_2025-04-03    England          ENG     4
4 2025-04-03  football_ranking_2025-04-03     Brazil          BRA     5

   previous_rank  rank_change  total_points  previous_points confederation  \
0              1            0       1886.16           1867.0          None
1              2            0       1868.74           1860.0          None
2              3            0       1857.08           1853.0          None
3              4            0       1819.20           1814.0          None
4              5            0       1776.04           1776.0          None

                                          source_url
0  https://football-ranking.com/ranks?period=03+A...
1  https://football-ranking.com/ranks?period=03+A...
2  https://football-ranking.com/ranks?period=03+A...
3  https://football-ranking.com/ranks?period=03+A...
4  https://football-ranking.com/ranks?period=03+A...
Saved ../data/fifa_rankings/fifa_ranking_2025-04-03.csv with shape (210, 11)

==============================
Processing: 2025-07-10 10 July 2025
==============================
Reading: https://football-ranking.com/ranks?period=10+July+2025
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=10+July+2025&page=2
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=10+July+2025&page=3
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=10+July+2025&page=4
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=10+July+2025&page=5
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (10, 11)
Downloaded shape: (210, 11)
   rank_date                      date_id    country country_code  rank  \
0 2025-07-10  football_ranking_2025-07-10  Argentina          ARG     1
1 2025-07-10  football_ranking_2025-07-10      Spain          ESP     2
2 2025-07-10  football_ranking_2025-07-10     France          FRA     3
3 2025-07-10  football_ranking_2025-07-10    England          ENG     4
4 2025-07-10  football_ranking_2025-07-10     Brazil          BRA     5

   previous_rank  rank_change  total_points  previous_points confederation  \
0              1            0       1885.36           1886.0          None
1              2            0       1867.09           1855.0          None
2              3            0       1862.03           1853.0          None
3              4            0       1813.32           1819.0          None
4              5            0       1777.68           1776.0          None

                                          source_url
0  https://football-ranking.com/ranks?period=10+J...
1  https://football-ranking.com/ranks?period=10+J...
2  https://football-ranking.com/ranks?period=10+J...
3  https://football-ranking.com/ranks?period=10+J...
4  https://football-ranking.com/ranks?period=10+J...
Saved ../data/fifa_rankings/fifa_ranking_2025-07-10.csv with shape (210, 11)

==============================
Processing: 2025-09-18 18 September 2025
==============================
Reading: https://football-ranking.com/ranks?period=18+September+2025
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=18+September+2025&page=2
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=18+September+2025&page=3
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=18+September+2025&page=4
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=18+September+2025&page=5
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (10, 11)
Downloaded shape: (210, 11)
   rank_date                      date_id    country country_code  rank  \
0 2025-09-18  football_ranking_2025-09-18      Spain          ESP     1
1 2025-09-18  football_ranking_2025-09-18     France          FRA     2
2 2025-09-18  football_ranking_2025-09-18  Argentina          ARG     3
3 2025-09-18  football_ranking_2025-09-18    England          ENG     4
4 2025-09-18  football_ranking_2025-09-18   Portugal          POR     5

   previous_rank  rank_change  total_points  previous_points confederation  \
0              2            1       1875.37           1867.0          None
1              3            1       1870.92           1862.0          None
2              1           -2       1870.33           1885.0          None
3              4            0       1820.45           1813.0          None
4              6            1       1779.56           1771.0          None

                                          source_url
0  https://football-ranking.com/ranks?period=18+S...
1  https://football-ranking.com/ranks?period=18+S...
2  https://football-ranking.com/ranks?period=18+S...
3  https://football-ranking.com/ranks?period=18+S...
4  https://football-ranking.com/ranks?period=18+S...
Saved ../data/fifa_rankings/fifa_ranking_2025-09-18.csv with shape (210, 11)

==============================
Processing: 2026-01-19 19 January 2026
==============================
Reading: https://football-ranking.com/ranks?period=19+January+2026
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=19+January+2026&page=2
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=19+January+2026&page=3
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=19+January+2026&page=4
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=19+January+2026&page=5
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (10, 11)
Downloaded shape: (210, 11)
   rank_date                      date_id    country country_code  rank  \
0 2026-01-19  football_ranking_2026-01-19      Spain          ESP     1
1 2026-01-19  football_ranking_2026-01-19  Argentina          ARG     2
2 2026-01-19  football_ranking_2026-01-19     France          FRA     3
3 2026-01-19  football_ranking_2026-01-19    England          ENG     4
4 2026-01-19  football_ranking_2026-01-19     Brazil          BRA     5

   previous_rank  rank_change  total_points  previous_points confederation  \
0              1            0       1877.18           1877.0          None
1              2            0       1873.33           1873.0          None
2              3            0       1870.00           1870.0          None
3              4            0       1834.12           1834.0          None
4              5            0       1760.46           1760.0          None

                                          source_url
0  https://football-ranking.com/ranks?period=19+J...
1  https://football-ranking.com/ranks?period=19+J...
2  https://football-ranking.com/ranks?period=19+J...
3  https://football-ranking.com/ranks?period=19+J...
4  https://football-ranking.com/ranks?period=19+J...
Saved ../data/fifa_rankings/fifa_ranking_2026-01-19.csv with shape (210, 11)

==============================
Processing: 2026-04-01 01 April 2026
==============================
Reading: https://football-ranking.com/ranks?period=01+April+2026
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=2
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=3
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=4
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (52, 11)
Reading: https://football-ranking.com/ranks?period=01+April+2026&page=5
Found 2 tables
Columns found: ['rank ↑↓', 'team', 'current point', 'prev. point', 'prev. rank']
Page shape: (10, 11)
Downloaded shape: (210, 11)
   rank_date                      date_id    country country_code  rank  \
0 2026-04-01  football_ranking_2026-04-01     France          FRA     1
1 2026-04-01  football_ranking_2026-04-01      Spain          ESP     2
2 2026-04-01  football_ranking_2026-04-01  Argentina          ARG     3
3 2026-04-01  football_ranking_2026-04-01    England          ENG     4
4 2026-04-01  football_ranking_2026-04-01   Portugal          POR     5

   previous_rank  rank_change  total_points  previous_points confederation  \
0              3            2       1877.32           1870.0          None
1              1           -1       1876.40           1877.0          None
2              2           -1       1874.82           1873.0          None
3              4            0       1825.97           1834.0          None
4              6            1       1763.83           1760.0          None

                                          source_url
0  https://football-ranking.com/ranks?period=01+A...
1  https://football-ranking.com/ranks?period=01+A...
2  https://football-ranking.com/ranks?period=01+A...
3  https://football-ranking.com/ranks?period=01+A...
4  https://football-ranking.com/ranks?period=01+A...
Saved ../data/fifa_rankings/fifa_ranking_2026-04-01.csv with shape (210, 11)

In [158]:
## Because of an error in parsing the dates we will use the september ranking from 2025 for matches after 2025-09-18 and before 2026-01-19. It is not ideal but it is valid just the ranks will be less up-to-date

In [177]:
## Merging all ranking csvs into one csv
ranking_dir = Path("../data/fifa_rankings")

ranking_files = [
    ranking_dir / "fifa_rankings_2022_2024_required_snapshots.csv",

    ranking_dir / "fifa_ranking_2025-04-03.csv",
    ranking_dir / "fifa_ranking_2025-07-10.csv",
    ranking_dir / "fifa_ranking_2025-09-18.csv",
    # ranking_dir / "fifa_ranking_2025-10-17.csv",  # include only if this one worked
    ranking_dir / "fifa_ranking_2026-01-19.csv",
    ranking_dir / "fifa_ranking_2026-04-01.csv"
]

In [178]:
ranking_dfs = []

for file_path in ranking_files:
    print("Reading:", file_path)

    df = pd.read_csv(file_path)

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
    )

    df["rank_date"] = pd.to_datetime(df["rank_date"])

    ranking_dfs.append(df)

fifa_rankings_2021_2026 = pd.concat(ranking_dfs, ignore_index=True)

Reading: ../data/fifa_rankings/fifa_rankings_2022_2024_required_snapshots.csv
Reading: ../data/fifa_rankings/fifa_ranking_2025-04-03.csv
Reading: ../data/fifa_rankings/fifa_ranking_2025-07-10.csv
Reading: ../data/fifa_rankings/fifa_ranking_2025-09-18.csv
Reading: ../data/fifa_rankings/fifa_ranking_2026-01-19.csv
Reading: ../data/fifa_rankings/fifa_ranking_2026-04-01.csv

In [179]:
fifa_rankings_2021_2026 = (
    fifa_rankings_2021_2026
    .drop_duplicates(subset=["rank_date", "country", "rank"])
    .sort_values(["rank_date", "rank"])
    .reset_index(drop=True)
)

In [180]:
output_path = ranking_dir / "fifa_rankings_2021-2026.csv"

fifa_rankings_2021_2026.to_csv(output_path, index=False)

print(f"Saved: {output_path}")
print(fifa_rankings_2021_2026.shape)

Saved: ../data/fifa_rankings/fifa_rankings_2021-2026.csv
(3573, 11)

In [181]:
fifa_rankings_2021_2026.groupby("rank_date").size()

rank_date
2021-12-23    210
2022-02-10    210
2022-03-31    211
2023-07-20    208
2023-09-21    207
2023-10-26    211
2024-02-15    211
2024-04-04    211
2024-07-18    211
2024-09-19    211
2024-10-24    211
2024-12-19    211
2025-04-03    210
2025-07-10    210
2025-09-18    210
2026-01-19    210
2026-04-01    210
dtype: int64

In [183]:
fifa_rankings_2021_2026[fifa_rankings_2021_2026['rank_date'] == '2026-04-01']

,rank_date,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,confederation,source_url
3363,2026-04-01,football_ranking_2026-04-01,France,FRA,1.0,3.0,2.0,1877.32,1870.0,NaN,https://football-ranking.com/ranks?period=01+A...
3364,2026-04-01,football_ranking_2026-04-01,Spain,ESP,2.0,1.0,-1.0,1876.40,1877.0,NaN,https://football-ranking.com/ranks?period=01+A...
3365,2026-04-01,football_ranking_2026-04-01,Argentina,ARG,3.0,2.0,-1.0,1874.82,1873.0,NaN,https://football-ranking.com/ranks?period=01+A...
3366,2026-04-01,football_ranking_2026-04-01,England,ENG,4.0,4.0,0.0,1825.97,1834.0,NaN,https://football-ranking.com/ranks?period=01+A...
3367,2026-04-01,football_ranking_2026-04-01,Portugal,POR,5.0,6.0,1.0,1763.83,1760.0,NaN,https://football-ranking.com/ranks?period=01+A...
...,...,...,...,...,...,...,...,...,...,...,...
3568,2026-04-01,football_ranking_2026-04-01,Bahamas,BAH,206.0,206.0,0.0,786.82,797.0,NaN,https://football-ranking.com/ranks?period=01+A...
3569,2026-04-01,football_ranking_2026-04-01,British Virgin Islands,VGB,207.0,208.0,1.0,782.14,777.0,NaN,https://football-ranking.com/ranks?period=01+A...
3570,2026-04-01,football_ranking_2026-04-01,US Virgin Islands,VIR,208.0,207.0,-1.0,779.77,777.0,NaN,https://football-ranking.com/ranks?period=01+A...
3571,2026-04-01,football_ranking_2026-04-01,Anguilla,AIA,209.0,209.0,0.0,760.25,760.0,NaN,https://football-ranking.com/ranks?period=01+A...
3572,2026-04-01,football_ranking_2026-04-01,San Marino,SMR,210.0,210.0,0.0,726.33,726.0,NaN,https://football-ranking.com/ranks?period=01+A...

In [184]:
fifa_rankings_2021_2026.isnull().sum()

rank_date             0
date_id               0
country               0
country_code          5
rank                 10
previous_rank        11
rank_change          11
total_points          0
previous_points       0
confederation      1050
source_url            0
dtype: int64

In [185]:
## Dropping the confederation column because it wont be necessary for our model
FIFA_rankings_21_26 = fifa_rankings_2021_2026.drop(columns='confederation').copy()
FIFA_rankings_21_26.isnull().sum()

rank_date           0
date_id             0
country             0
country_code        5
rank               10
previous_rank      11
rank_change        11
total_points        0
previous_points     0
source_url          0
dtype: int64

In [186]:
FIFA_rankings_21_26[FIFA_rankings_21_26.isna().any(axis=1)]

,rank_date,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,source_url
609,2022-03-31,id13603,Cook Islands,COK,190.0,NaN,NaN,899.33,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1253,2023-10-26,id14177,American Samoa,ASA,NaN,NaN,NaN,900.27,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1254,2023-10-26,id14177,Samoa,SAM,NaN,NaN,NaN,894.26,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1255,2023-10-26,id14177,Tonga,TGA,NaN,NaN,NaN,861.81,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1256,2023-10-26,id14177,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1467,2024-02-15,id14289,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1678,2024-04-04,id14338,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
1889,2024-07-18,id14443,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
2100,2024-09-19,id14506,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
2311,2024-10-24,id14541,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
2522,2024-12-19,id14597,Eritrea,ERI,NaN,NaN,NaN,855.56,0.0,https://inside.fifa.com/fifa-world-ranking/men...
2592,2025-04-03,football_ranking_2025-04-03,atOptions = { 'key' : '70c6397f984309008567c7...,NaN,70.0,70.0,0.0,70.00,70.0,https://football-ranking.com/ranks?period=03+A...
2802,2025-07-10,football_ranking_2025-07-10,atOptions = { 'key' : '70c6397f984309008567c7...,NaN,70.0,70.0,0.0,70.00,70.0,https://football-ranking.com/ranks?period=10+J...
3012,2025-09-18,football_ranking_2025-09-18,atOptions = { 'key' : '70c6397f984309008567c7...,NaN,70.0,70.0,0.0,70.00,70.0,https://football-ranking.com/ranks?period=18+S...
3222,2026-01-19,football_ranking_2026-01-19,atOptions = { 'key' : '70c6397f984309008567c7...,NaN,70.0,70.0,0.0,70.00,70.0,https://football-ranking.com/ranks?period=19+J...
3432,2026-04-01,football_ranking_2026-04-01,atOptions = { 'key' : '70c6397f984309008567c7...,NaN,70.0,70.0,0.0,70.00,70.0,https://football-ranking.com/ranks?period=01+A...

In [188]:
FIFA_rankings_21_26_without_NA = FIFA_rankings_21_26.dropna().copy()

In [189]:
FIFA_rankings_21_26_without_NA.isnull().sum()

rank_date          0
date_id            0
country            0
country_code       0
rank               0
previous_rank      0
rank_change        0
total_points       0
previous_points    0
source_url         0
dtype: int64

In [190]:
FIFA_rankings_21_26_without_NA

,rank_date,date_id,country,country_code,rank,previous_rank,rank_change,total_points,previous_points,source_url
0,2021-12-23,id13505,Belgium,BEL,1.0,1.0,0.0,1828.45,1828.45,https://inside.fifa.com/fifa-world-ranking/men...
1,2021-12-23,id13505,Brazil,BRA,2.0,2.0,0.0,1826.35,1826.35,https://inside.fifa.com/fifa-world-ranking/men...
2,2021-12-23,id13505,France,FRA,3.0,3.0,0.0,1786.15,1786.15,https://inside.fifa.com/fifa-world-ranking/men...
3,2021-12-23,id13505,England,ENG,4.0,4.0,0.0,1755.52,1755.52,https://inside.fifa.com/fifa-world-ranking/men...
4,2021-12-23,id13505,Argentina,ARG,5.0,5.0,0.0,1750.51,1750.51,https://inside.fifa.com/fifa-world-ranking/men...
...,...,...,...,...,...,...,...,...,...,...
3568,2026-04-01,football_ranking_2026-04-01,Bahamas,BAH,206.0,206.0,0.0,786.82,797.00,https://football-ranking.com/ranks?period=01+A...
3569,2026-04-01,football_ranking_2026-04-01,British Virgin Islands,VGB,207.0,208.0,1.0,782.14,777.00,https://football-ranking.com/ranks?period=01+A...
3570,2026-04-01,football_ranking_2026-04-01,US Virgin Islands,VIR,208.0,207.0,-1.0,779.77,777.00,https://football-ranking.com/ranks?period=01+A...
3571,2026-04-01,football_ranking_2026-04-01,Anguilla,AIA,209.0,209.0,0.0,760.25,760.00,https://football-ranking.com/ranks?period=01+A...
3572,2026-04-01,football_ranking_2026-04-01,San Marino,SMR,210.0,210.0,0.0,726.33,726.00,https://football-ranking.com/ranks?period=01+A...

In [191]:
FIFA_rankings_21_26_without_NA.to_csv("../data/ProcessedDataForTestModel/FIFA_rankings_2021_2026.csv")

In [ ]:
## We added the FIFA rankings without null values to the folder where the historical match data is located, the next step is to attach correct power rankings to home/away teams in the historical match data