In [14]:
import pandas as pd

In [15]:
summary = pd.read_csv('./experiment_summary_v1.csv')
summary_2 = pd.read_csv('./experiment_summary_final.csv')

In [16]:
summary

,Unnamed: 0,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,20,Experiment_3-3_ranks_SMA_best,0.665315,0.621989,0.570723,0.808193,0.539833,0.022527,0.510902,0.576542
1,19,Experiment_3-2_ranks_EMA_best,0.662162,0.604942,0.562522,0.805570,0.520582,0.028504,0.482418,0.572219
2,24,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699
3,18,Experiment_3-1_ELO_SMA5,0.653659,0.442671,0.544461,0.789481,0.482207,0.010277,0.469020,0.507548
4,22,Experiment_3-5_ranks_diff_EMA_diff,0.647748,0.527921,0.542014,0.795909,0.485990,0.012086,0.468846,0.509872
5,23,Experiment_3-6_ranks_diff_EMA_diff_SMA_diff,0.641892,0.561969,0.538360,0.793885,0.492479,0.018033,0.468259,0.527373
6,13,Experiment_2-8_SMA5_diff,0.634959,0.417811,0.518304,0.776105,0.459157,0.013585,0.439470,0.467594
7,7,Experiment_2-2_SMA5,0.634146,0.415264,0.522900,0.778010,0.461470,0.005674,0.452252,0.470846
8,14,Experiment_2-9_SMA7_diff,0.620690,0.417249,0.529630,0.761786,0.464646,0.000000,0.464646,0.464646
9,8,Experiment_2-3_SMA7,0.619540,0.407531,0.527037,0.765435,0.458450,0.006009,0.446199,0.467819
10,6,Experiment_2-1_SMA3,0.597647,0.378156,0.474680,0.754143,0.419203,0.006685,0.412913,0.437461
11,21,Experiment_3-4_ranks_diff_SMA5_diff,0.595122,0.385093,0.515939,0.774646,0.440939,0.003976,0.434289,0.445511
12,12,Experiment_2-7_SMA3_diff,0.588235,0.375955,0.470691,0.750689,0.413554,0.000676,0.412913,0.414196
13,3,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
14,0,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
15,5,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
16,4,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
17,2,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
18,1,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412
19,10,Experiment_2-5_EMA33,0.531532,0.362971,0.441753,0.721968,0.377097,0.006419,0.368838,0.387239
20,11,Experiment_2-6_EMA25,0.525225,0.354233,0.436375,0.719495,0.371138,0.005497,0.363632,0.381287
21,9,Experiment_2-4_EMA50,0.522072,0.355562,0.429591,0.715683,0.363844,0.016197,0.346959,0.389628
22,15,Experiment_2-10_EMA50_diff,0.521622,0.338004,0.446214,0.724903,0.378002,0.003653,0.374307,0.386420
23,16,Experiment_2-11_EMA33_diff,0.521171,0.339826,0.439394,0.721564,0.372655,0.002079,0.369658,0.374037
24,17,Experiment_2-12_EMA25_diff,0.515766,0.332175,0.447090,0.724482,0.377616,0.004549,0.372344,0.385859

In [17]:
summary_2

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_2-1_v2_points_SMA3,0.614414,0.407906,0.486550,0.764602,0.436351,0.004363,0.428821,0.440540
1,Experiment_2-2_v2_points_SMA5,0.611261,0.406803,0.491142,0.764140,0.440510,0.003866,0.434390,0.446700
2,Experiment_2-2_v2_points_SMA7,0.589189,0.390179,0.477972,0.753139,0.427142,0.008222,0.413967,0.440362
3,Experiment_2-4_v2_points_EMA50,0.595045,0.395404,0.471002,0.752572,0.422449,0.004834,0.414872,0.428483
4,Experiment_2-5_v2_points_EMA33,0.607207,0.405814,0.484219,0.760267,0.434738,0.008643,0.425418,0.448478
5,Experiment_2-6_v2_points_EMA25,0.613514,0.409809,0.495594,0.765713,0.444350,0.009171,0.421156,0.456417
6,Experiment_2-8_v2_points_SMA5_Diff,0.612162,0.409099,0.494056,0.764650,0.443087,0.008024,0.430423,0.449766
7,Experiment_2-9_v2_points_SMA7_Diff,0.598198,0.398914,0.490117,0.758409,0.438098,0.001816,0.434652,0.438960
8,Experiment_2-10_v2_points_EMA50_Diff,0.582883,0.382885,0.465128,0.748461,0.415612,0.005026,0.406283,0.421819
9,Experiment_2-11_v2_points_EMA33_Diff,0.596847,0.393342,0.479138,0.757090,0.428442,0.004873,0.416627,0.435388
10,Experiment_2-12_v2_points_EMA25_Diff,0.610360,0.401167,0.495571,0.767810,0.441629,0.004323,0.439261,0.453363
11,Experiment_3-1_v2_points_ranks_SMA5,0.663514,0.563037,0.562998,0.806355,0.521787,0.037189,0.481409,0.583942
12,Experiment_3-2_v2_points_ranks_EMA25,0.657207,0.573534,0.560157,0.804454,0.521997,0.032467,0.477321,0.571251
13,Experiment_3-3_v2_points_ranks_SMA5_EMA25,0.663964,0.609983,0.573808,0.808421,0.552603,0.013435,0.527727,0.571725
14,Experiment_2-7_v2_points_SMA3_Diff,0.590090,0.382098,0.472494,0.756464,0.420350,0.000000,0.420350,0.420350
15,Experiment_3-4_v2_points_rank_diff_elo_diff_SMA5,0.649099,0.558660,0.542883,0.795996,0.491110,0.011958,0.471566,0.507644
16,Experiment_3-4_v2_points_rank_diff_elo_diff_EMA25,0.648198,0.527566,0.541228,0.795469,0.490926,0.014286,0.472487,0.515485
17,Experiment_3-5_v2_points_rank_diff_elo_diff_EMA25,0.648198,0.527566,0.541228,0.795469,0.490926,0.014286,0.472487,0.515485
18,Experiment_3-6_v2_points_rank_diff_elo_diff_SM...,0.643694,0.524578,0.539546,0.793762,0.498575,0.014160,0.479981,0.523961
19,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412
20,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
21,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
22,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
23,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
24,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
25,Experiment_2-1_SMA3,0.597647,0.378156,0.474680,0.754143,0.419203,0.006685,0.412913,0.437461
26,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699

In [18]:
summary_2 = summary_2.drop(index=[16, 25]).reset_index(drop=True)
summary_2

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_2-1_v2_points_SMA3,0.614414,0.407906,0.486550,0.764602,0.436351,0.004363,0.428821,0.440540
1,Experiment_2-2_v2_points_SMA5,0.611261,0.406803,0.491142,0.764140,0.440510,0.003866,0.434390,0.446700
2,Experiment_2-2_v2_points_SMA7,0.589189,0.390179,0.477972,0.753139,0.427142,0.008222,0.413967,0.440362
3,Experiment_2-4_v2_points_EMA50,0.595045,0.395404,0.471002,0.752572,0.422449,0.004834,0.414872,0.428483
4,Experiment_2-5_v2_points_EMA33,0.607207,0.405814,0.484219,0.760267,0.434738,0.008643,0.425418,0.448478
5,Experiment_2-6_v2_points_EMA25,0.613514,0.409809,0.495594,0.765713,0.444350,0.009171,0.421156,0.456417
6,Experiment_2-8_v2_points_SMA5_Diff,0.612162,0.409099,0.494056,0.764650,0.443087,0.008024,0.430423,0.449766
7,Experiment_2-9_v2_points_SMA7_Diff,0.598198,0.398914,0.490117,0.758409,0.438098,0.001816,0.434652,0.438960
8,Experiment_2-10_v2_points_EMA50_Diff,0.582883,0.382885,0.465128,0.748461,0.415612,0.005026,0.406283,0.421819
9,Experiment_2-11_v2_points_EMA33_Diff,0.596847,0.393342,0.479138,0.757090,0.428442,0.004873,0.416627,0.435388
10,Experiment_2-12_v2_points_EMA25_Diff,0.610360,0.401167,0.495571,0.767810,0.441629,0.004323,0.439261,0.453363
11,Experiment_3-1_v2_points_ranks_SMA5,0.663514,0.563037,0.562998,0.806355,0.521787,0.037189,0.481409,0.583942
12,Experiment_3-2_v2_points_ranks_EMA25,0.657207,0.573534,0.560157,0.804454,0.521997,0.032467,0.477321,0.571251
13,Experiment_3-3_v2_points_ranks_SMA5_EMA25,0.663964,0.609983,0.573808,0.808421,0.552603,0.013435,0.527727,0.571725
14,Experiment_2-7_v2_points_SMA3_Diff,0.590090,0.382098,0.472494,0.756464,0.420350,0.000000,0.420350,0.420350
15,Experiment_3-4_v2_points_rank_diff_elo_diff_SMA5,0.649099,0.558660,0.542883,0.795996,0.491110,0.011958,0.471566,0.507644
16,Experiment_3-5_v2_points_rank_diff_elo_diff_EMA25,0.648198,0.527566,0.541228,0.795469,0.490926,0.014286,0.472487,0.515485
17,Experiment_3-6_v2_points_rank_diff_elo_diff_SM...,0.643694,0.524578,0.539546,0.793762,0.498575,0.014160,0.479981,0.523961
18,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412
19,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
20,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
21,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
22,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
23,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
24,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699

In [25]:
summary_2 = summary_2.sort_values('accuracy', ascending=False)
summary_2.reset_index(drop=True)

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_3-3_v2_points_ranks_SMA5_EMA25,0.663964,0.609983,0.573808,0.808421,0.552603,0.013435,0.527727,0.571725
1,Experiment_3-1_v2_points_ranks_SMA5,0.663514,0.563037,0.562998,0.806355,0.521787,0.037189,0.481409,0.583942
2,Experiment_3-2_v2_points_ranks_EMA25,0.657207,0.573534,0.560157,0.804454,0.521997,0.032467,0.477321,0.571251
3,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699
4,Experiment_3-4_v2_points_rank_diff_elo_diff_SMA5,0.649099,0.558660,0.542883,0.795996,0.491110,0.011958,0.471566,0.507644
5,Experiment_3-5_v2_points_rank_diff_elo_diff_EMA25,0.648198,0.527566,0.541228,0.795469,0.490926,0.014286,0.472487,0.515485
6,Experiment_3-6_v2_points_rank_diff_elo_diff_SM...,0.643694,0.524578,0.539546,0.793762,0.498575,0.014160,0.479981,0.523961
7,Experiment_2-1_v2_points_SMA3,0.614414,0.407906,0.486550,0.764602,0.436351,0.004363,0.428821,0.440540
8,Experiment_2-6_v2_points_EMA25,0.613514,0.409809,0.495594,0.765713,0.444350,0.009171,0.421156,0.456417
9,Experiment_2-8_v2_points_SMA5_Diff,0.612162,0.409099,0.494056,0.764650,0.443087,0.008024,0.430423,0.449766
10,Experiment_2-2_v2_points_SMA5,0.611261,0.406803,0.491142,0.764140,0.440510,0.003866,0.434390,0.446700
11,Experiment_2-12_v2_points_EMA25_Diff,0.610360,0.401167,0.495571,0.767810,0.441629,0.004323,0.439261,0.453363
12,Experiment_2-5_v2_points_EMA33,0.607207,0.405814,0.484219,0.760267,0.434738,0.008643,0.425418,0.448478
13,Experiment_2-9_v2_points_SMA7_Diff,0.598198,0.398914,0.490117,0.758409,0.438098,0.001816,0.434652,0.438960
14,Experiment_2-11_v2_points_EMA33_Diff,0.596847,0.393342,0.479138,0.757090,0.428442,0.004873,0.416627,0.435388
15,Experiment_2-4_v2_points_EMA50,0.595045,0.395404,0.471002,0.752572,0.422449,0.004834,0.414872,0.428483
16,Experiment_2-7_v2_points_SMA3_Diff,0.590090,0.382098,0.472494,0.756464,0.420350,0.000000,0.420350,0.420350
17,Experiment_2-2_v2_points_SMA7,0.589189,0.390179,0.477972,0.753139,0.427142,0.008222,0.413967,0.440362
18,Experiment_2-10_v2_points_EMA50_Diff,0.582883,0.382885,0.465128,0.748461,0.415612,0.005026,0.406283,0.421819
19,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
20,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
21,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
22,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
23,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
24,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412

In [22]:
summary = summary.sort_values('accuracy', ascending=False)
summary.reset_index(drop=True)
summary.drop(columns='Unnamed: 0', inplace=True)
summary

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_3-3_ranks_SMA_best,0.665315,0.621989,0.570723,0.808193,0.539833,0.022527,0.510902,0.576542
1,Experiment_3-2_ranks_EMA_best,0.662162,0.604942,0.562522,0.805570,0.520582,0.028504,0.482418,0.572219
2,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699
3,Experiment_3-1_ELO_SMA5,0.653659,0.442671,0.544461,0.789481,0.482207,0.010277,0.469020,0.507548
4,Experiment_3-5_ranks_diff_EMA_diff,0.647748,0.527921,0.542014,0.795909,0.485990,0.012086,0.468846,0.509872
5,Experiment_3-6_ranks_diff_EMA_diff_SMA_diff,0.641892,0.561969,0.538360,0.793885,0.492479,0.018033,0.468259,0.527373
6,Experiment_2-8_SMA5_diff,0.634959,0.417811,0.518304,0.776105,0.459157,0.013585,0.439470,0.467594
7,Experiment_2-2_SMA5,0.634146,0.415264,0.522900,0.778010,0.461470,0.005674,0.452252,0.470846
8,Experiment_2-9_SMA7_diff,0.620690,0.417249,0.529630,0.761786,0.464646,0.000000,0.464646,0.464646
9,Experiment_2-3_SMA7,0.619540,0.407531,0.527037,0.765435,0.458450,0.006009,0.446199,0.467819
10,Experiment_2-1_SMA3,0.597647,0.378156,0.474680,0.754143,0.419203,0.006685,0.412913,0.437461
11,Experiment_3-4_ranks_diff_SMA5_diff,0.595122,0.385093,0.515939,0.774646,0.440939,0.003976,0.434289,0.445511
12,Experiment_2-7_SMA3_diff,0.588235,0.375955,0.470691,0.750689,0.413554,0.000676,0.412913,0.414196
13,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
14,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
15,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
16,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
17,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
18,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412
19,Experiment_2-5_EMA33,0.531532,0.362971,0.441753,0.721968,0.377097,0.006419,0.368838,0.387239
20,Experiment_2-6_EMA25,0.525225,0.354233,0.436375,0.719495,0.371138,0.005497,0.363632,0.381287
21,Experiment_2-4_EMA50,0.522072,0.355562,0.429591,0.715683,0.363844,0.016197,0.346959,0.389628
22,Experiment_2-10_EMA50_diff,0.521622,0.338004,0.446214,0.724903,0.378002,0.003653,0.374307,0.386420
23,Experiment_2-11_EMA33_diff,0.521171,0.339826,0.439394,0.721564,0.372655,0.002079,0.369658,0.374037
24,Experiment_2-12_EMA25_diff,0.515766,0.332175,0.447090,0.724482,0.377616,0.004549,0.372344,0.385859

In [23]:
summary.to_csv('./experiment_summary_v1.csv')

In [28]:
summary_2 = pd.read_csv('./experiment_summary_final.csv')
summary_2

,Unnamed: 0,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,13,Experiment_3-3_v2_points_ranks_SMA5_EMA25,0.663964,0.609983,0.573808,0.808421,0.552603,0.013435,0.527727,0.571725
1,11,Experiment_3-1_v2_points_ranks_SMA5,0.663514,0.563037,0.562998,0.806355,0.521787,0.037189,0.481409,0.583942
2,12,Experiment_3-2_v2_points_ranks_EMA25,0.657207,0.573534,0.560157,0.804454,0.521997,0.032467,0.477321,0.571251
3,24,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699
4,15,Experiment_3-4_v2_points_rank_diff_elo_diff_SMA5,0.649099,0.558660,0.542883,0.795996,0.491110,0.011958,0.471566,0.507644
5,16,Experiment_3-5_v2_points_rank_diff_elo_diff_EMA25,0.648198,0.527566,0.541228,0.795469,0.490926,0.014286,0.472487,0.515485
6,17,Experiment_3-6_v2_points_rank_diff_elo_diff_SM...,0.643694,0.524578,0.539546,0.793762,0.498575,0.014160,0.479981,0.523961
7,0,Experiment_2-1_v2_points_SMA3,0.614414,0.407906,0.486550,0.764602,0.436351,0.004363,0.428821,0.440540
8,5,Experiment_2-6_v2_points_EMA25,0.613514,0.409809,0.495594,0.765713,0.444350,0.009171,0.421156,0.456417
9,6,Experiment_2-8_v2_points_SMA5_Diff,0.612162,0.409099,0.494056,0.764650,0.443087,0.008024,0.430423,0.449766
10,1,Experiment_2-2_v2_points_SMA5,0.611261,0.406803,0.491142,0.764140,0.440510,0.003866,0.434390,0.446700
11,10,Experiment_2-12_v2_points_EMA25_Diff,0.610360,0.401167,0.495571,0.767810,0.441629,0.004323,0.439261,0.453363
12,4,Experiment_2-5_v2_points_EMA33,0.607207,0.405814,0.484219,0.760267,0.434738,0.008643,0.425418,0.448478
13,7,Experiment_2-9_v2_points_SMA7_Diff,0.598198,0.398914,0.490117,0.758409,0.438098,0.001816,0.434652,0.438960
14,9,Experiment_2-11_v2_points_EMA33_Diff,0.596847,0.393342,0.479138,0.757090,0.428442,0.004873,0.416627,0.435388
15,3,Experiment_2-4_v2_points_EMA50,0.595045,0.395404,0.471002,0.752572,0.422449,0.004834,0.414872,0.428483
16,14,Experiment_2-7_v2_points_SMA3_Diff,0.590090,0.382098,0.472494,0.756464,0.420350,0.000000,0.420350,0.420350
17,2,Experiment_2-2_v2_points_SMA7,0.589189,0.390179,0.477972,0.753139,0.427142,0.008222,0.413967,0.440362
18,8,Experiment_2-10_v2_points_EMA50_Diff,0.582883,0.382885,0.465128,0.748461,0.415612,0.005026,0.406283,0.421819
19,21,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
20,19,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
21,22,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
22,23,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
23,20,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
24,18,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412

In [29]:
summary_2.drop(columns='Unnamed: 0', inplace= True)
summary_2

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_3-3_v2_points_ranks_SMA5_EMA25,0.663964,0.609983,0.573808,0.808421,0.552603,0.013435,0.527727,0.571725
1,Experiment_3-1_v2_points_ranks_SMA5,0.663514,0.563037,0.562998,0.806355,0.521787,0.037189,0.481409,0.583942
2,Experiment_3-2_v2_points_ranks_EMA25,0.657207,0.573534,0.560157,0.804454,0.521997,0.032467,0.477321,0.571251
3,Experiment_4-1_FIFA_rank_goal_diff_EMA,0.655856,0.610702,0.554263,0.799931,0.508386,0.018636,0.472394,0.529699
4,Experiment_3-4_v2_points_rank_diff_elo_diff_SMA5,0.649099,0.558660,0.542883,0.795996,0.491110,0.011958,0.471566,0.507644
5,Experiment_3-5_v2_points_rank_diff_elo_diff_EMA25,0.648198,0.527566,0.541228,0.795469,0.490926,0.014286,0.472487,0.515485
6,Experiment_3-6_v2_points_rank_diff_elo_diff_SM...,0.643694,0.524578,0.539546,0.793762,0.498575,0.014160,0.479981,0.523961
7,Experiment_2-1_v2_points_SMA3,0.614414,0.407906,0.486550,0.764602,0.436351,0.004363,0.428821,0.440540
8,Experiment_2-6_v2_points_EMA25,0.613514,0.409809,0.495594,0.765713,0.444350,0.009171,0.421156,0.456417
9,Experiment_2-8_v2_points_SMA5_Diff,0.612162,0.409099,0.494056,0.764650,0.443087,0.008024,0.430423,0.449766
10,Experiment_2-2_v2_points_SMA5,0.611261,0.406803,0.491142,0.764140,0.440510,0.003866,0.434390,0.446700
11,Experiment_2-12_v2_points_EMA25_Diff,0.610360,0.401167,0.495571,0.767810,0.441629,0.004323,0.439261,0.453363
12,Experiment_2-5_v2_points_EMA33,0.607207,0.405814,0.484219,0.760267,0.434738,0.008643,0.425418,0.448478
13,Experiment_2-9_v2_points_SMA7_Diff,0.598198,0.398914,0.490117,0.758409,0.438098,0.001816,0.434652,0.438960
14,Experiment_2-11_v2_points_EMA33_Diff,0.596847,0.393342,0.479138,0.757090,0.428442,0.004873,0.416627,0.435388
15,Experiment_2-4_v2_points_EMA50,0.595045,0.395404,0.471002,0.752572,0.422449,0.004834,0.414872,0.428483
16,Experiment_2-7_v2_points_SMA3_Diff,0.590090,0.382098,0.472494,0.756464,0.420350,0.000000,0.420350,0.420350
17,Experiment_2-2_v2_points_SMA7,0.589189,0.390179,0.477972,0.753139,0.427142,0.008222,0.413967,0.440362
18,Experiment_2-10_v2_points_EMA50_Diff,0.582883,0.382885,0.465128,0.748461,0.415612,0.005026,0.406283,0.421819
19,Experiment_1-4_ELO_diff,0.581048,0.473523,0.503769,0.774730,0.480450,0.012963,0.461922,0.504922
20,Experiment_1-2_ELO_ranks,0.572581,0.427533,0.497456,0.754513,0.433007,0.018120,0.417060,0.467679
21,Experiment_1-5_FIFA_and_ELO_ranks,0.568952,0.402301,0.491572,0.751598,0.424636,0.012667,0.412022,0.456008
22,Experiment_1-6_FIFA_and_ELO_ranks_diff,0.568952,0.413672,0.497432,0.755846,0.428113,0.005285,0.423412,0.438543
23,Experiment_1-3_ranks_diff,0.566532,0.373747,0.494069,0.754653,0.421205,0.002389,0.418061,0.423412
24,Experiment_1-1_FIFA_ranks,0.562097,0.375536,0.485993,0.749323,0.416145,0.005403,0.409589,0.423412

In [30]:
summary_2.to_csv('./experiment_summary_final.csv')

In [1]:
import pandas as pd

data = pd.read_csv('./experiment_summary_activation_change.csv')
data

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_3-3_v2_points_ranks_SMA5_EMA25_Leak...,0.663964,0.608420,0.575447,0.809385,0.554985,0.016436,0.527521,0.578063
1,Experiment_3-3_v2_points_ranks_SMA5_EMA25_GELU,0.645495,0.576934,0.562929,0.803115,0.544797,0.020660,0.508181,0.574115
2,Experiment_3-3_ranks_SMA_best_EMA_best_LeakyRELU,0.658108,0.593227,0.563580,0.804655,0.534161,0.019074,0.501170,0.560791
3,Experiment_3-3_ranks_SMA_best_EMA_best_GELU,0.656757,0.589727,0.558832,0.802470,0.518824,0.034307,0.474411,0.566585

In [3]:
data = data.sort_values('accuracy', ascending=False)
data.reset_index(drop=True)
data

,experiment,accuracy,precision,recall,specificity,f1,f1_std,f1_min,f1_max
0,Experiment_3-3_v2_points_ranks_SMA5_EMA25_Leak...,0.663964,0.608420,0.575447,0.809385,0.554985,0.016436,0.527521,0.578063
2,Experiment_3-3_ranks_SMA_best_EMA_best_LeakyRELU,0.658108,0.593227,0.563580,0.804655,0.534161,0.019074,0.501170,0.560791
3,Experiment_3-3_ranks_SMA_best_EMA_best_GELU,0.656757,0.589727,0.558832,0.802470,0.518824,0.034307,0.474411,0.566585
1,Experiment_3-3_v2_points_ranks_SMA5_EMA25_GELU,0.645495,0.576934,0.562929,0.803115,0.544797,0.020660,0.508181,0.574115

In [4]:
data.to_csv('./experiment_summary_activation_change.csv')